services:
  - type: web
    name: dev-deck-ultimate
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py" # Use python directly to run the threaded app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8279866700:AAEZ_-0B4NDHlnrhrj81a6knakqdlCWRRlg"
      - key: PYTHON_VERSION
        value: 3.10.6
